---
# Variables here are applicable to all host groups
status_dir: "{{ deploy_dir }}/status"
backup_dir: "{{ deploy_dir }}/backup"
images_dir: "{{ deploy_dir }}/images"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
fetch_log_dir: "{{ playbook_dir }}/fetch_logfile"

# default configuration for multiple host groups and roles
node_exporter_port: 9100

# docker
docker_bin_dir: "/usr/bin"

# Adjust time server
# time_server: pool.ntp.org

deploy_dir: /home/tidb/deploy

## Connection
# ssh via root:
# ansible_user: root
# ansible_become: true
# ansible_become_user: tidb

# ssh via normal user
ansible_user: tidb

cluster_name: test-cluster

tidb_version: latest

# deployment methods, [binary, docker]
deployment_method: binary

# process supervision, [systemd, supervise]
process_supervision: systemd

# timezone of deployment region
timezone: Asia/Shanghai

# misc
enable_elk: False
enable_firewalld: False
enable_ntpd: True
machine_benchmark: True
set_hostname: False

# binlog trigger
enable_binlog: False
# store slow query log into seperate file
enable_slow_query_log: False

cloud_provider:

