---

- name: do AWS preparation
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - include_vars:
        file: "{{ playbook_dir }}/vars.yml"
  roles:
    - aws
  post_tasks:
    - name: display hosts
      debug: msg="run `ansible-playbook aws_inventory_file_generate.yml` to get your aws.ini!"
